### PR TITLE
nmg.py 

### PR DESCRIPTION
**Pull request by nathanmgroom**
Augmented 500 * 10 photos
-Nathan

### CODE REVIEW

**Comment by muxspace** [comment]
Is this for the image transformations or images for the base data set? If your images are from the celebrity database, then please remove those along with the entries in legend.csv. The image transformation code should not include the images/legend because it will be too big for github. As I said in the lecture, they will need to be applied at run time so must not be included in the pull request.

**Comment by nathanmgroom** [comment]
Hi Prof. Rowe,
You'll have to forgive me, I'm still learning how to use Github. I do
remember the instructions, I think I just did it wrong. The problem I think
I'm having is I'm unsure how to submit a pull request for just 1 item. My
Python script, nmg.py, is one of many files in this forked repository. How
do I direct it to pull just that particular file? When I click on New Pull
Request, it shows a list of every commit I've ever made to this repository.
This is where I get lost. What do I do from here to tell it to only submit
a pull request for one file?

Thank you Professor,
Nathan

**Comment by nathanmgroom** [comment]
Hi Professor,
I actually think I figured this out. If you check the pull requests you
should be able to see my Python file, no photos etc., as per the
instructions. Sorry for my previous error.

Nathan

**Comment by nathanmgroom** [comment]
Okay great. Worst case scenario is to copy the script out of the directory, re clone my version of the repo, and then move it into the new repo.
On Nov 10, 2016 03:50, "nathanmgroom ." nathanmgroom@gmail.com wrote:Hi Professor,I actually think I figured this out. If you check the pull requests you should be able to see my Python file, no photos etc., as per the instructions. Sorry for my previous error.NathanOn Wed, Nov 9, 2016 at 10:16 AM, nathanmgroom . nathanmgroom@gmail.com wrote:Hi Prof. Rowe,You'll have to forgive me, I'm still learning how to use Github. I do remember the instructions, I think I just did it wrong. The problem I think I'm having is I'm unsure how to submit a pull request for just 1 item. My Python script, nmg.py, is one of many files in this forked repository. How do I direct it to pull just that particular file? When I click on New Pull Request, it shows a list of every commit I've ever made to this repository. This is where I get lost. What do I do from here to tell it to only submit a pull request for one file?Thank you Professor,NathanOn Wed, Nov 9, 2016 at 5:59 AM, Brian Lee Yung Rowe notifications@github.com wrote:Closed #32.

**Pull request closed without merging**
