### PR TITLE
Sandipayan Image Augmentation  python script

### PR DESCRIPTION
**Pull request by sandipayan**
Python script  - 

	sandipayan	Sandipayan image aug script			0777df0

### CODE REVIEW

**Comment by sandipayan** [comment]
sandipayan image augmentation script

**Comment by sandipayan** [comment]
ss

**Comment by muxspace** [comment]
The image transformation code should not include the images/legend because it will be too big for github. As I said in the lecture, they will need to be applied at run time so must not be included in the pull request.

**Comment by sandipayan** [comment]
Hi Professor Rowe, 
 I was not able to send pull request only for the .py code from my forked & cloned repository, so I did send the pull request for the whole folder. I hoped that you will be able to pull only the necessary .py file and ignoring other., i.e.    0777df0  file. 

If that cannot be done, please let me know and I will fork ,clone and add my .py file and send another pull request.

**Pull request closed without merging**
