### PR TITLE
Ppadebettu patch 2

### PR DESCRIPTION
**Pull request by ppadebettu**
the metadata .csv file and the images are committed here

### CODE REVIEW

**Comment by muxspace** [comment]
You need to use the file name `legend.csv`

**Comment by ppadebettu** [comment]
Hello Prof. Rowe, the file is already named as "legend.csv" and is available at the following location
https://github.com/ppadebettu/facial_expressions/tree/master/data

Please let me know if this helps.

**Comment by muxspace** [comment]
If this pull request is related to images in the celebrity database, please close it.

**Comment by ppadebettu** [comment]
Closing the pull request as they are related to images in the celebrity database.

**Pull request closed without merging**
